# Generated by Django 3.1.4 on 2020-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='external_id',
            field=models.IntegerField(verbose_name='Внешний ID'),
        ),
    ]
