# Generated by Django 3.1.4 on 2020-12-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201220_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='filial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.filial', verbose_name='name'),
        ),
    ]
