# Generated by Django 3.1.4 on 2020-12-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_region_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cekh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Цеха')),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.region', verbose_name='name')),
            ],
        ),
    ]
