# Generated by Django 3.1.4 on 2020-12-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cekh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cekh',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.filial', verbose_name='name'),
        ),
    ]
