# Generated by Django 3.1.4 on 2020-12-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cekh_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cekh',
            name='region',
        ),
    ]
