# Generated by Django 3.1.4 on 2020-12-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201224_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cekh',
            old_name='filial',
            new_name='region',
        ),
    ]
